site_name: 2 Day Python Bootcamp
site_url: https://qurioskill.github.io/Python-Bootcamp/
theme:
  name: material
  language: en
  logo: assets/logo.jpg
  palette:
    - scheme: default
      primary: amber
      accent: Turquoise Green
  features:
    - navigation.instant       # fast page transitions
    - navigation.sections
    - search.highlight
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github # icon repo
nav:
  - Bootcamp: index.md
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed
