site_name: Python Bootcamp
site_url: https://qurioskill.github.io/Python-Bootcamp/
theme:
  name: material
  language: en
  logo: assets/logo.jpg
  palette:
    - scheme: default
      primary: amber
      accent: Turquoise Green
  features:
    - navigation.instant       # fast page transitions
    - navigation.sections
    - search.highlight
    - content.code.annotate    # call-out markers in code blocks
nav:
  - Overview: index.md
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed